version: '3'

services:
  frontend:
    build: 
       context: ./VPTDashboard    
    ports:
      - "4201:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./VPTDashboard-FastAPI  
    ports:
      - "9000:9000"  
